# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-21 02:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20191021_0122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricepolicy',
            old_name='table_name',
            new_name='content_type',
        ),
        migrations.RemoveField(
            model_name='pricepolicy',
            name='object_id',
        ),
    ]
