# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-21 02:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20191021_0201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricepolicy',
            name='content_type',
        ),
        migrations.DeleteModel(
            name='PricePolicy',
        ),
    ]
